Cargo.toml
src/errno.rs
src/helper.rs
src/raw/connection.rs
src/raw/session.rs

Nix 0.22.0 implements From in both directions between Nix::Error and
io::Error.

Update Nix to the latest, which changes error types

---

Cargo.toml
examples/src/memfs/main.rs
examples/src/path_memfs/main.rs
src/helper.rs
src/lib.rs
src/mount_options.rs
src/raw/connection.rs
src/raw/session.rs

* Use a newer Nix, with nmount support.
* Use nmount on FreeBSD instead of mount.
* Deal with 16-bit mode_t
* Disable fallocate in some examples, not yet supported by FreeBSD's fusefs
* Do nothing special to mount without privileges on FreeBSD.  Unlike Linux,
it will just work if the system is configured to allow it.
* Open /dev/fuse with O_NONBLOCK, rather than setting it later.
* Set fs_name in one of the examples, for demonstration purposes.
Note: FreeBSD 14.0-CURRENT is required, with a build from
7b8622fa220b9c08041102f638f848c48e022644 or later.

Port to FreeBSD

---

src/raw/filesystem.rs

The FUSE protocol specifies that the response to FUSE_GETXATTR is a data
buffer without header when sending data, or a struct fuse_getxattr_out
when sending the attribute's size.  However, since the data buffer does
not include a header it is impossible for the kernel to distinguish
between a struct fuse_getxattr_out and a data buffer if exactly the same
size.  Therefore, FUSE servers must always return ERANGE if the provided
size was insufficient.

Document that getxattr *must* return ERANGE if the size is insufficient

---

examples/src/memfs/main.rs
examples/src/path_memfs/main.rs
src/raw/reply.rs

The fuse_write_in struct only uses 32 bits to request the size of the
write, so there's no point to allocating 64 bits for the response.

Change ReplyWrite.written to 32 bits

---

src/raw/request.rs

It's helpful when unit testing a fuse3-based file system.

derive Default for Request

---

src/raw/session.rs

With size=0, the file system should reply with the size of the list and
errno 0.  errno ERANGE should only be used if the request had a nonzero
size that was too small.

Fix FUSE_LISTXATTR with size=0

---

src/path/inode_path_bridge.rs
src/path/path_filesystem.rs
src/raw/filesystem.rs
src/raw/session.rs

It's perfectly valid for an extended attribute to have binary data with
one, many, or no NUL characters.  fuse3 therefore can't convert it into
an OsString.  Pass the byte slice to the file system instead.
Fixes #14

Change setxattr's value argument to a &[u8]

---

examples/src/helloworld/main.rs
examples/src/memfs/main.rs
examples/src/path_memfs/main.rs
examples/src/poll/main.rs
src/path/inode_path_bridge.rs
src/path/reply.rs
src/raw/reply.rs
src/raw/session.rs

The FUSE protocol allows each directory entry to include a off field in
struct fuse_dirent. It's purpose is to uniquely identify a directory
entry so that a future FUSE_READDIR operation may continue where a
previous one left off. The FUSE file system is allowed to choose the
format of those off values. In particular, sequentially increasing
indexes are usually not adequate, because if a directory entry is
deleted in between two FUSE_READDIR operations, using sequential off
values could lead to skipping over a directory entry.
Instead of attempting to manage those offsets with fuse3, forcing them
to be sequential, pass responsibility to the file system.
Fixes #12

Allow non-sequential directory offsets

---

src/path/path_filesystem.rs
src/raw/filesystem.rs
src/raw/session.rs

This makes it work nicely with FUSE_NO_OPENDIR_SUPPORT and mirrors the
behavior for FUSE_OPEN.

By default return ENOSYS for FUSE_OPENDIR

---

examples/src/helloworld/main.rs
examples/src/memfs/main.rs
examples/src/path_memfs/main.rs
examples/src/poll/main.rs
src/mount_options.rs
src/raw/session.rs

The consuming methods make for a nice compact syntax - as long as the
programmer knows exactly which methods will be needed.  But if some
mount options depend on runtime options then the consuming methods are
awkward:
```
let mut opts = MountOptions::default();
if let Some(foo) = cli.bar {
opts = opts.custom_options(foo)
}
```
Non-consuming options, while requiring 1 more line in the simplest case,
are more flexible.
While I'm here, remove some extraneous clone()s.

Use no-consuming methods for MountOptions

---

examples/src/helloworld/main.rs
examples/src/memfs/main.rs
examples/src/path_memfs/main.rs
examples/src/poll/main.rs
src/path/session.rs
src/raw/mod.rs
src/raw/session.rs

Session::mount will now return a Future that completes when the mount
does, whose result is another Future that completes when the file system
is unmounted.  This allows consumers to know whether the mount succeeded
without waiting for a future unmount.
Fixes #27

Make Session::mount semi-synchronous

---

Cargo.toml

It makes no difference to fuse3 itself, but it allows consuming crates to potentially build fewer versions of Nix.

Raise Nix dependency to 0.26.1

---

Cargo.toml
src/raw/session.rs

This is removing an unnecessary crate dependency with no loss of readability.

Replace dependency on tokio-stream with function call.

---

src/raw/session.rs

This fix can be verified with the helloworld example. Without the fix, it complains about the mountpoint not being empty even when it is:
```shellSession
$ mkdir /tmp/mountpoint
$ cargo run --bin helloworld -- /tmp/mountpoint
...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', examples/src/helloworld/main.rs:336:10
...
```
The problem is that, on an empty dir, `read_dir(mount_path).await?.next_entry().await` returns `Ok(None)`, but the nonempty check only makes sense if it finds `Ok(Some(...))`. I was going to write this check as `.is_ok_and(Option::is_some)` instead, but `Result::is_ok_and` is unstable.
@KongzhangHao FYI: It appears that this issue was introduced in #53.

fix mount with tokio-runtime and nonempty = true

---

examples/src/memfs/main.rs
src/raw/connection.rs

https://github.com/Sherlock-Holo/fuse3/issues/4#issuecomment-1379976922
we check the kernel codes that the /dev/fuse is always writable, there's
no need to use AsyncFd(tokio)/Async(async-std) to check if the /dev/fuse
fd is writable or not

Remove connection writable wait

---

Cargo.toml

nix 0.26.1 contains bugs and mainline contains pull requests for unsound behavior. It seems unnecessary to track a specific minor version so just depend on 0.26.x instead.
If this seems OK, could you also bump the release version and push to crates.io for me?

Drop minor version dependency for nix.

---

src/raw/session.rs

Fixed error "body length is not right" when handling any FUSE_SETXATTR request.
Before fix, we checked size of full payload "Name"+"Value", but setxattr.size field specifies only size of "Value" field.
Moved size check procedure down to proper place after payload splitting to "Name" and "Value".
Now we compare setxattr.size field with size of "Value" field.

Fixed fuse setxattr body length is not right error

---

Cargo.toml
examples/src/memfs/main.rs
examples/src/path_memfs/main.rs
src/path/inode_path_bridge.rs
src/path/path_filesystem.rs
src/raw/filesystem.rs
src/raw/flags.rs
src/raw/mod.rs
src/raw/session.rs

add `write_flags` in the `write` method, user can use it check if the write operation is a delay write or not

feat: add write_flags arguments in the write method

---

src/raw/session.rs

when MountHandle .await is completed, drop MountHandle will poll the inner task again, then will cause a panic

fix: MountHandle cause panic

---

src/notify.rs
src/raw/abi.rs
src/raw/connection/async_io.rs
src/raw/connection/tokio.rs
src/raw/reply.rs
src/raw/session.rs

Mostly, clean up a lot of unused fields, delete some unused structs (but leave them commented out in case somebody implements FUSE_IOCTL), and clean up some use statements.

Clippy cleanup

---

Cargo.lock
Cargo.toml
src/mount_options.rs
src/raw/session.rs

This eliminates the cstr and syn-1 crates, and raises MSRV to 1.77.0
Fixes #93

Use native CStr literals

---

src/raw/session.rs

On FreeBSD, the same procedure is used to mount a fuse file system whether or not the process is privileged.

Remove a misleading doc comment

---

src/raw/connection/tokio.rs

It's adding `tokio::io::Interrest::ERROR` to the list of awaited state changes. 
Otherwise we don't get `ENODEV` which signals `Fuse` unmount events.
Fixes: https://github.com/Sherlock-Holo/fuse3/issues/102

Fix the unmount notification for unprivileged mounts.

---

.cirrus.yml
Cargo.lock
Cargo.toml
examples/Cargo.toml
src/helper.rs
src/lib.rs
src/mount_options.rs
src/path/inode_path_bridge.rs
src/path/reply.rs
src/raw/abi.rs
src/raw/connection/async_io.rs
src/raw/connection/tokio.rs
src/raw/reply.rs
src/raw/session.rs

recreate https://github.com/Sherlock-Holo/fuse3/pull/90

feat: introduce macos support

---

src/raw/reply.rs

Many of the types in fuse3 already implement Debug, but there are exceptions.  ReplyDirectory and ReplyDirectoryPlus do not, possibly because implementing unconditionally would force DirEntryPlusStream and DirEntryStream implementations to also implement Debug.
This change conditionally implements Debug for ReplyDirectory and ReplyDirectoryPlus, in the cases where the stream types also already implement Debug.

Implement Debug in more places
